// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdoptiumAsset = {
  binary: AdoptiumBinary;
  release_name: string;
  version: AdoptiumVersionData;
};

export type AdoptiumBinary = {
  os: string;
  architecture: string;
  image_type: string;
  package: AdoptiumPackage;
  updated_at: string | null;
};

export type AdoptiumPackage = {
  name: string;
  link: string;
  size: bigint;
  checksum: string | null;
};

export type AdoptiumVersionData = {
  major: number;
  minor: number;
  security: number;
  semver: string;
  openjdk_version: string;
};

export type AvailableReleases = {
  available_releases: Array<number>;
  available_lts_releases: Array<number>;
  most_recent_lts: number | null;
  most_recent_feature_release: number | null;
};
