name: 功能请求（中文）
description: 为 DropOut 提出新功能或改进建议
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您提出新功能建议！请填写以下表单以帮助我们理解您的需求。

  - type: checkboxes
    id: prerequisites
    attributes:
      label: 前置确认
      description: 请确认自己完成了下列项目之后再进行勾选，若勾选了"我未仔细阅读"选项将视为自愿接受被直接关闭 Issue
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息
          required: false
        - label: 我未仔细阅读这些内容，只是一键已读所有内容，并相信这不会影响问题的处理
          required: false
        - label: 我已搜索现有 Issue，确认这不是重复的功能请求
          required: false
        - label: 我已查看 README 中的 Roadmap
          required: false
        - label: 这个功能将使多个用户受益，而不仅仅是我自己
          required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型
      description: 您请求的是哪种类型的功能？
      options:
        - UI/UX 改进
        - 游戏管理
        - Mod 加载器支持
        - 账户管理
        - Java 管理
        - 性能优化
        - 新平台支持
        - 文档
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题陈述
      description: 您的功能请求是否与某个问题相关？请描述。
      placeholder: "我总是对...感到困扰"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 描述您希望看到的解决方案
      placeholder: 清晰简洁地描述您希望发生的事情...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 描述您考虑过的任何替代解决方案或功能
      placeholder: 是否有其他方法可以解决这个问题？
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: 示例和参考
      description: |
        提供其他启动器或应用程序实现类似功能的示例
      placeholder: |
        - MultiMC 通过...实现
        - Prism Launcher 有类似功能...
        - 可以像 [示例链接] 这样工作...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 这个功能对您有多重要？
      options:
        - 关键（阻碍正常使用）
        - 高（显著改善体验）
        - 中（锦上添花）
        - 低（小便利）
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      description: 您是否愿意为这个功能做出贡献？
      options:
        - label: 我愿意实现这个功能
        - label: 我愿意帮助测试这个功能
        - label: 我可以提供设计草图或规范

  - type: textarea
    id: additional
    attributes:
      label: 其他信息
      description: 在此添加关于功能请求的任何其他信息、草图或截图
      placeholder: 任何可能有帮助的额外信息...
    validations:
      required: false
