// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfflineAccount } from "./auth";

export type AccountStorage = { file_path: string };

/**
 * Stored account data for persistence
 */
export type AccountStore = {
  accounts: Array<StoredAccount>;
  active_account_id: string | null;
};

export type StoredAccount =
  | ({ type: "Offline" } & OfflineAccount)
  | ({ type: "Microsoft" } & StoredMicrosoftAccount);

/**
 * Microsoft account with refresh token for persistence
 */
export type StoredMicrosoftAccount = {
  username: string;
  uuid: string;
  access_token: string;
  refresh_token: string | null;
  ms_refresh_token: string | null;
  expires_at: bigint;
};
