// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssistantConfig = {
  enabled: boolean;
  llmProvider: string;
  ollamaEndpoint: string;
  ollamaModel: string;
  openaiApiKey: string | null;
  openaiEndpoint: string;
  openaiModel: string;
  systemPrompt: string;
  responseLanguage: string;
  ttsEnabled: boolean;
  ttsProvider: string;
};

/**
 * Feature-gated arguments configuration
 */
export type FeatureFlags = {
  /**
   * Demo user: enables demo-related arguments when rules require it
   */
  demoUser: boolean;
  /**
   * Quick Play: enable quick play arguments
   */
  quickPlayEnabled: boolean;
  /**
   * Quick Play singleplayer world path (if provided)
   */
  quickPlayPath: string | null;
  /**
   * Quick Play singleplayer flag
   */
  quickPlaySingleplayer: boolean;
  /**
   * Quick Play multiplayer server address (optional)
   */
  quickPlayMultiplayerServer: string | null;
};

export type LauncherConfig = {
  minMemory: number;
  maxMemory: number;
  javaPath: string;
  width: number;
  height: number;
  downloadThreads: number;
  customBackgroundPath: string | null;
  enableGpuAcceleration: boolean;
  enableVisualEffects: boolean;
  activeEffect: string;
  theme: string;
  logUploadService: string;
  pastebinApiKey: string | null;
  assistant: AssistantConfig;
  useSharedCaches: boolean;
  keepLegacyPerInstanceStorage: boolean;
  featureFlags: FeatureFlags;
};
