// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a Forge version entry.
 */
export type ForgeVersion = {
  version: string;
  minecraftVersion: string;
  recommended: boolean;
  latest: boolean;
};

/**
 * Information about an installed Forge version.
 */
export type InstalledForgeVersion = {
  id: string;
  minecraftVersion: string;
  forgeVersion: string;
  path: string;
};
