// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JavaCatalog = {
  releases: Array<JavaReleaseInfo>;
  availableMajorVersions: Array<number>;
  ltsVersions: Array<number>;
  cachedAt: bigint;
};

export type JavaDownloadInfo = {
  version: string;
  release_name: string;
  download_url: string;
  file_name: string;
  file_size: bigint;
  checksum: string | null;
  image_type: string;
};

export type JavaInstallation = {
  path: string;
  version: string;
  arch: string;
  vendor: string;
  source: string;
  is64bit: boolean;
};

export type JavaReleaseInfo = {
  majorVersion: number;
  imageType: string;
  version: string;
  releaseName: string;
  releaseDate: string | null;
  fileSize: bigint;
  checksum: string | null;
  downloadUrl: string;
  isLts: boolean;
  isAvailable: boolean;
  architecture: string;
};
