// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JavaConfig = {
  user_defined_paths: Array<string>;
  preferred_java_path: string | null;
  last_detection_time: bigint;
};
