// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GenerationStats = {
  totalDuration: bigint;
  loadDuration: bigint;
  promptEvalCount: bigint;
  promptEvalDuration: bigint;
  evalCount: bigint;
  evalDuration: bigint;
};

export type Message = { role: string; content: string };

export type ModelInfo = {
  id: string;
  name: string;
  size: string | null;
  details: string | null;
};

export type StreamChunk = {
  content: string;
  done: boolean;
  stats: GenerationStats | null;
};
