// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Latest = { release: string; snapshot: string };

export type Version = {
  id: string;
  type: string;
  url: string;
  time: string;
  releaseTime: string;
  /**
   * Java version requirement (major version number)
   * This is populated from the version JSON file if the version is installed locally
   */
  javaVersion: bigint | null;
  /**
   * Whether this version is installed locally
   */
  isInstalled: boolean | null;
};

export type VersionManifest = { latest: Latest; versions: Array<Version> };
